package SimpleReaderBackupDecoder;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.DialogInterface;
import android.content.SharedPreferences;
import android.content.pm.ApplicationInfo;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.TextView;
import java.io.File;
import java.lang.reflect.Method;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
public final class kt {
private static final String PREF = "operation_history_v726";
private static final int LIMIT = 10;
private static final String MODE_ALL = "all_books";
private static final String MODE_NO_CATALOG = "books_without_catalog";
private static final Pattern PROGRESS = Pattern.compile("(?:^|\\n)\\s*(\\d+)\\s*/\\s*(\\d+)");
private static final Pattern BOOK_PROGRESS = Pattern.compile("（\\s*(\\d+)\\s*/\\s*(\\d+)\\s*）\\s*$");
private static Context lastContext;
private static String lastMode = "";
private kt() {}
private static Context app(Context context) { if (context == null) return null; Context a = context.getApplicationContext(); return a != null ? a : context; }
private static void purgeLegacy(Context context) { if (context == null) return; try { ApplicationInfo info = context.getApplicationInfo(); if (info == null || info.dataDir == null) return; File dir = new File(info.dataDir, "shared_prefs"); new File(dir, "operation.xml").delete(); new File(dir, "operation.xml.bak").delete(); } catch (Throwable ignored) {} }
private static String modeTitle(String mode) { if (MODE_NO_CATALOG.equals(mode)) return "全书架无目录书籍缓存"; if (MODE_ALL.equals(mode)) return "全书架目录缓存"; return "书架目录缓存"; }
private static void startNewTask(SharedPreferences sp, String mode, long now) {
int count = Math.min(LIMIT, Math.max(0, sp.getInt("count", 0))); SharedPreferences.Editor e = sp.edit(); int move = Math.min(count, LIMIT - 1);
for (int i = move; i >= 1; i--) { e.putString("title_" + i, sp.getString("title_" + (i - 1), "目录缓存")); e.putString("body_" + i, sp.getString("body_" + (i - 1), "")); }
count = Math.min(LIMIT, count + 1); e.putInt("count", count); e.putString("title_0", modeTitle(mode) + " · " + stamp(now)); e.putInt("active", 1); e.putString("mode", mode); e.putLong("started_at", now); e.putLong("last_update", now); e.putInt("scan_total", 0); e.putInt("target_total", 0); e.putInt("excluded_success", 0); e.putInt("completed_count", 0); e.putInt("failed_count", 0); e.putInt("skipped_count", 0); e.putInt("run_offset", 0); e.putInt("last_current", 0); e.putString("last_title", ""); e.putInt("pending", 0); e.putString("failure_details", ""); e.putString("skip_details", ""); e.apply();
}
private static void ensureModeTask(Context app, String mode) {
if (app == null) return; purgeLegacy(app); SharedPreferences sp = app.getSharedPreferences(PREF, Context.MODE_PRIVATE); boolean active = sp.getInt("active", 0) == 1; int count = Math.min(LIMIT, Math.max(0, sp.getInt("count", 0))); String savedMode = sp.getString("mode", ""); long now = System.currentTimeMillis();
if (!active || count == 0) startNewTask(sp, mode, now); else { SharedPreferences.Editor e = sp.edit().putString("mode", mode); if (savedMode == null || savedMode.length() == 0) { long started = sp.getLong("started_at", now); e.putString("title_0", modeTitle(mode) + " · " + stamp(started)); } e.apply(); }
try { KeepAliveService.start(app); } catch (Throwable ignored) {} updateBody(app, "准备中", "");
}
public static synchronized void record(Context context, String message) { try { recordMessageSafe(context, message); } catch (Throwable ignored) {} }
private static void recordMessageSafe(Context context, String message) {
if (context == null || message == null) return; Context a = app(context); if (a == null) return; lastContext = a;
if (MODE_ALL.equals(message) || MODE_NO_CATALOG.equals(message)) { SharedPreferences sp = a.getSharedPreferences(PREF, Context.MODE_PRIVATE); if (MODE_NO_CATALOG.equals(message) && sp.getInt("active", 0) == 1 && MODE_NO_CATALOG.equals(sp.getString("mode", "")) && sp.getInt("pending", 0) == 1) { classifyPending(a, "skip", "扫描后已存在可用目录缓存"); return; } lastMode = message; ensureModeTask(a, message); return; }
boolean initial = message.contains("生成目录"); if (initial) { SharedPreferences sp = a.getSharedPreferences(PREF, Context.MODE_PRIVATE); if (sp.getInt("active", 0) != 1) startNewTask(sp, "", System.currentTimeMillis()); return; }
Matcher b = BOOK_PROGRESS.matcher(message); if (b.find()) { SharedPreferences sp = a.getSharedPreferences(PREF, Context.MODE_PRIVATE); if (sp.getInt("active", 0) != 1) return; finalizePendingSuccess(a); int rawCurrent = safeInt(b.group(1)); int rawTotal = safeInt(b.group(2)); int offset = sp.getInt("run_offset", 0); String title = message.substring(0, b.start()).trim(); SharedPreferences.Editor e = sp.edit(); e.putInt("last_current", Math.max(0, offset + rawCurrent)); e.putString("last_title", title); e.putInt("pending", 1); if (sp.getInt("target_total", 0) <= 0) e.putInt("target_total", Math.max(0, offset + rawTotal)); e.putLong("last_update", System.currentTimeMillis()); e.apply(); updateBody(a, "运行中", title); return; }
if (message.startsWith("失败：")) { SharedPreferences sp = a.getSharedPreferences(PREF, Context.MODE_PRIVATE); if (sp.getInt("active", 0) == 1 && sp.getInt("pending", 0) == 1) classifyPending(a, "fail", message.substring("失败：".length())); return; }
Matcher p = PROGRESS.matcher(message); boolean plainProgress = p.find(); boolean terminal = message.contains("成功") && message.contains("失败") && message.contains("跳过");
if (terminal) { finalizePendingSuccess(a); SharedPreferences sp = a.getSharedPreferences(PREF, Context.MODE_PRIVATE); int target = sp.getInt("target_total", 0); int classified = classified(sp); if (target <= 0) { target = classified; sp.edit().putInt("target_total", target).apply(); } sp.edit().putInt("active", 0).putLong("last_update", System.currentTimeMillis()).apply(); updateBody(a, classified == target ? "已完成" : "完成但存在未归类", ""); try { KeepAliveService.stop(a); } catch (Throwable ignored) {} return; }
if (plainProgress) updateBody(a, "运行中", "");
}
public static synchronized Object record(Object value) { try { return filterBooksSafe(value); } catch (Throwable ignored) { return value; } }
private static Object filterBooksSafe(Object value) {
if (!(value instanceof List)) return value; Context a = lastContext; if (a == null) return value; String mode = lastMode; if (mode == null || mode.length() == 0) mode = a.getSharedPreferences(PREF, Context.MODE_PRIVATE).getString("mode", ""); List<?> books = (List<?>) value; int scanTotal = books.size(); List<Object> targets = new ArrayList<Object>(); int excluded = 0;
if (MODE_ALL.equals(mode)) { clearAllDerived(a); targets.addAll((List<Object>) books); } else if (MODE_NO_CATALOG.equals(mode)) { CacheProbe probe = new CacheProbe(a); for (Object book : books) { if (book != null && probe.hasReusableCurrentCache(book)) excluded++; else targets.add(book); } } else return value;
SharedPreferences sp = a.getSharedPreferences(PREF, Context.MODE_PRIVATE); int alreadyClassified = classified(sp); boolean resumed = sp.getInt("last_current", 0) > 0 || alreadyClassified > 0; int targetTotal = resumed ? Math.max(sp.getInt("target_total", 0), alreadyClassified + targets.size()) : targets.size(); SharedPreferences.Editor e = sp.edit(); e.putInt("scan_total", scanTotal); if (!resumed) e.putInt("excluded_success", excluded); e.putInt("target_total", targetTotal); e.putInt("run_offset", resumed ? alreadyClassified : 0); e.putInt("last_current", resumed ? alreadyClassified : 0); e.putString("last_title", ""); e.putInt("pending", 0); e.putLong("last_update", System.currentTimeMillis()); e.apply(); updateBody(a, targets.isEmpty() ? "已完成" : "运行中", ""); if (targets.isEmpty()) { sp.edit().putInt("active", 0).apply(); try { KeepAliveService.stop(a); } catch (Throwable ignored) {} } return targets;
}
private static final class CacheProbe {
private final Context context; private Class<?> bookClass; private Method getId; private Method getFileName; private Method getFileSize; private Method getFilePath; private Object loader; private Method resolveDocument; private Method loadDocument; private Method docGetName; private Method docLength; private Method readerDocGetText; private Method readerDocGetSourceSize; private Method readerDocGetSourceModified; private Object profile; private Method currentTextSizeSp; private Method createSettings; private Method stableHash; private Object pageStore; private Method hasCurrentCatalog; private Method textFingerprint; private Method loadPages; private java.lang.reflect.Constructor<?> cacheIdentityCtor; private Method readerBookGetPages; private int catalogRuleVersion = 111; private boolean ready;
CacheProbe(Context context) { this.context = context; try { bookClass = Class.forName("com.simplereader.app.data.entity.Book"); getId = bookClass.getMethod("getId"); getFileName = bookClass.getMethod("getFileName"); getFileSize = bookClass.getMethod("getFileSize"); getFilePath = bookClass.getMethod("getFilePath"); Class<?> loaderClass = Class.forName("com.simplereader.app.reader.ReaderDocumentLoader"); loader = loaderClass.getField("INSTANCE").get(null); resolveDocument = loaderClass.getMethod("resolveDocument", Context.class, bookClass); loadDocument = loaderClass.getMethod("load", Context.class, bookClass, boolean.class); Class<?> documentFileClass = Class.forName("androidx.documentfile.provider.DocumentFile"); docGetName = documentFileClass.getMethod("getName"); docLength = documentFileClass.getMethod("length"); Class<?> readerDocClass = Class.forName("com.simplereader.app.reader.ReaderDocument"); readerDocGetText = readerDocClass.getMethod("getText"); readerDocGetSourceSize = readerDocClass.getMethod("getSourceSize"); readerDocGetSourceModified = readerDocClass.getMethod("getSourceModified"); Class<?> profileClass = Class.forName("com.simplereader.app.reader.page.ReaderCacheProfile"); profile = profileClass.getField("INSTANCE").get(null); currentTextSizeSp = profileClass.getMethod("currentTextSizeSp", Context.class); createSettings = profileClass.getMethod("createSettings", Context.class, float.class, Integer.class, Integer.class, Integer.class, Integer.class, Integer.class, Integer.class); Class<?> settingsClass = Class.forName("com.simplereader.app.reader.page.ReaderLayoutSettings"); stableHash = settingsClass.getMethod("stableHash"); Class<?> pageClass = Class.forName("com.simplereader.app.reader.page.PageCacheStore"); pageStore = pageClass.getField("INSTANCE").get(null); hasCurrentCatalog = pageClass.getMethod("hasCurrentCatalog", Context.class, long.class, String.class, Long.class); textFingerprint = pageClass.getMethod("textFingerprint", String.class); Class<?> identityClass = Class.forName("com.simplereader.app.reader.page.PageCacheStore$CacheIdentity"); cacheIdentityCtor = identityClass.getConstructor(long.class, String.class, long.class, long.class, String.class, String.class, int.class); loadPages = pageClass.getMethod("loadPages", Context.class, identityClass, String.class); Class<?> readerBookClass = Class.forName("com.simplereader.app.reader.page.ReaderBook"); readerBookGetPages = readerBookClass.getMethod("getPages"); try { Class<?> txtParser = Class.forName("com.simplereader.app.parser.TxtParser"); catalogRuleVersion = txtParser.getField("CATALOG_RULE_VERSION").getInt(null); } catch (Throwable ignored) { catalogRuleVersion = 111; } ready = true; } catch (Throwable ignored) { ready = false; } }
boolean hasReusableCurrentCache(Object book) { if (!ready || book == null) return false; try { long id = ((Number) getId.invoke(book)).longValue(); String fileName = (String) getFileName.invoke(book); Long fileSize = (Long) getFileSize.invoke(book); String filePath = (String) getFilePath.invoke(book); Object source = resolveDocument.invoke(loader, context, book); if (source != null) { Object n = docGetName.invoke(source); if (n instanceof String && ((String) n).trim().length() > 0) fileName = (String) n; Object length = docLength.invoke(source); if (length instanceof Number) { long len = ((Number) length).longValue(); if (len >= 0L) fileSize = Long.valueOf(len); } } Object catalog = hasCurrentCatalog.invoke(pageStore, context, Long.valueOf(id), fileName, fileSize); if (!Boolean.TRUE.equals(catalog)) return false; Object document = loadDocument.invoke(loader, context, book, Boolean.FALSE); if (document == null) return false; String text = (String) readerDocGetText.invoke(document); if (text == null) return false; long sourceSize = ((Number) readerDocGetSourceSize.invoke(document)).longValue(); long sourceModified = ((Number) readerDocGetSourceModified.invoke(document)).longValue(); float textSize = ((Number) currentTextSizeSp.invoke(profile, context)).floatValue(); Object settings = createSettings.invoke(profile, context, Float.valueOf(textSize), null, null, null, null, null, null); if (settings == null) return false; String settingsHash = (String) stableHash.invoke(settings); String fingerprint = (String) textFingerprint.invoke(pageStore, text); Object identity = cacheIdentityCtor.newInstance(Long.valueOf(id), filePath, Long.valueOf(sourceSize), Long.valueOf(sourceModified), settingsHash, fingerprint, Integer.valueOf(catalogRuleVersion)); Object cached = loadPages.invoke(pageStore, context, identity, text); if (cached == null) return false; Object pages = readerBookGetPages.invoke(cached); return pages instanceof List && !((List<?>) pages).isEmpty(); } catch (Throwable ignored) { return false; } }
}
private static void clearAllDerived(Context context) { try { Class<?> pageClass = Class.forName("com.simplereader.app.reader.page.PageCacheStore"); Object store = pageClass.getField("INSTANCE").get(null); Method clear = pageClass.getMethod("clearAllDerivedCatalogAndPages", Context.class); clear.invoke(store, context); } catch (Throwable ignored) {} }
private static void finalizePendingSuccess(Context a) { SharedPreferences sp = a.getSharedPreferences(PREF, Context.MODE_PRIVATE); if (sp.getInt("pending", 0) != 1) return; SharedPreferences.Editor e = sp.edit(); e.putInt("completed_count", sp.getInt("completed_count", 0) + 1); e.putInt("pending", 0); e.putLong("last_update", System.currentTimeMillis()); e.apply(); }
private static void classifyPending(Context a, String outcome, String reason) { SharedPreferences sp = a.getSharedPreferences(PREF, Context.MODE_PRIVATE); if (sp.getInt("pending", 0) != 1) return; String title = sp.getString("last_title", ""); SharedPreferences.Editor e = sp.edit().putInt("pending", 0).putLong("last_update", System.currentTimeMillis()); if ("fail".equals(outcome)) { e.putInt("failed_count", sp.getInt("failed_count", 0) + 1); String detail = sp.getString("failure_details", ""); String stage = failureStage(reason); String line = "- " + (title == null || title.length() == 0 ? "（未知书名）" : title) + "\n  阶段：" + stage + "\n  原因：" + cleanReason(reason) + "\n"; e.putString("failure_details", (detail == null ? "" : detail) + line); } else if ("skip".equals(outcome)) { e.putInt("skipped_count", sp.getInt("skipped_count", 0) + 1); String detail = sp.getString("skip_details", ""); String line = "- " + (title == null || title.length() == 0 ? "（未知书名）" : title) + "：" + cleanReason(reason) + "\n"; e.putString("skip_details", (detail == null ? "" : detail) + line); } e.apply(); updateBody(a, "运行中", ""); }
private static String failureStage(String raw) { String s = raw == null ? "" : raw; if (s.contains("分页结果为空")) return "分页"; if (s.contains("缓存写入") || s.contains("缓存页数") || s.contains("章节校验") || s.contains("重新读取")) return "分页缓存写入/校验"; if (s.contains("SecurityException") || s.contains("Permission") || s.contains("EACCES")) return "文件访问权限"; if (s.contains("FileNotFound") || s.contains("NoSuchFile") || s.contains("ENOENT") || s.contains("文件")) return "文件读取"; if (s.contains("OutOfMemory")) return "分页/内存"; if (s.contains("目录") || s.contains("chapter") || s.contains("Chapter")) return "目录识别"; return "目录识别/分页处理"; }
private static String cleanReason(String raw) { if (raw == null || raw.trim().length() == 0) return "未知异常（未提供异常文本）"; String s = raw.replace('\n', ' ').replace('\r', ' ').trim(); return s.length() > 1200 ? s.substring(0, 1200) + "…" : s; }
private static int classified(SharedPreferences sp) { return sp.getInt("completed_count", 0) + sp.getInt("failed_count", 0) + sp.getInt("skipped_count", 0); }
private static void updateBody(Context a, String state, String currentTitle) { SharedPreferences sp = a.getSharedPreferences(PREF, Context.MODE_PRIVATE); int count = Math.min(LIMIT, Math.max(0, sp.getInt("count", 0))); if (count <= 0) return; String mode = sp.getString("mode", lastMode == null ? "" : lastMode); long started = sp.getLong("started_at", System.currentTimeMillis()); long now = System.currentTimeMillis(); int scan = Math.max(0, sp.getInt("scan_total", 0)); int target = Math.max(0, sp.getInt("target_total", 0)); int excluded = Math.max(0, sp.getInt("excluded_success", 0)); int success = Math.max(0, sp.getInt("completed_count", 0)); int failed = Math.max(0, sp.getInt("failed_count", 0)); int skipped = Math.max(0, sp.getInt("skipped_count", 0)); int done = success + failed + skipped; int pending = sp.getInt("pending", 0) == 1 ? 1 : 0; int shownCurrent = Math.min(target, done + pending); double percent = target > 0 ? shownCurrent * 100.0 / target : ("已完成".equals(state) ? 100.0 : 0.0); int unclassified = Math.max(0, target - done); String failures = sp.getString("failure_details", ""); String skips = sp.getString("skip_details", ""); StringBuilder body = new StringBuilder(); body.append("操作：").append(modeTitle(mode)).append("（目录识别 + 完整分页缓存）\n"); body.append("状态：").append(state).append("\n"); body.append("开始：").append(fullStamp(started)).append("\n"); body.append("更新：").append(fullStamp(now)).append("\n"); if (scan > 0) body.append("扫描书架：").append(scan).append(" 本\n"); if (MODE_NO_CATALOG.equals(mode)) body.append("已成功可复用（排除）：").append(excluded).append(" 本\n"); body.append("本次目标：").append(target).append(" 本\n"); body.append("处理进度：").append(shownCurrent).append(" / ").append(target).append("（").append(String.format(Locale.getDefault(), "%.1f", percent)).append("%）\n"); if (currentTitle != null && currentTitle.length() > 0) body.append("当前：").append(currentTitle).append("\n"); else { String last = sp.getString("last_title", ""); if (sp.getInt("pending", 0) == 1 && last != null && last.length() > 0) body.append("当前：").append(last).append("\n"); } body.append("成功：").append(success).append(" 本；失败：").append(failed).append(" 本；跳过：").append(skipped).append(" 本\n"); if (("已完成".equals(state) || state.contains("未归类")) && unclassified > 0) body.append("未归类：").append(unclassified).append(" 本（日志事件未完整闭合，禁止视为完全成功）\n"); if (failed > 0) { body.append("\n失败明细：\n"); body.append(failures == null || failures.length() == 0 ? "- 有失败计数，但未捕获异常文本\n" : failures); } if (skipped > 0) { body.append("\n跳过明细：\n"); body.append(skips == null ? "" : skips); } sp.edit().putString("title_0", modeTitle(mode) + " · " + stamp(started)).putString("body_0", body.toString()).putLong("last_update", now).apply(); }
public static void show(final Activity activity) { if (activity == null || activity.isFinishing()) return; purgeLegacy(activity); final SharedPreferences sp = activity.getSharedPreferences(PREF, Context.MODE_PRIVATE); int count = Math.min(LIMIT, Math.max(0, sp.getInt("count", 0))); if (count <= 0) { new AlertDialog.Builder(activity).setTitle("操作日志").setMessage("暂无操作日志").setNegativeButton("关闭", null).show(); return; } final CharSequence[] titles = new CharSequence[count]; for (int i = 0; i < count; i++) titles[i] = sp.getString("title_" + i, "目录缓存"); new AlertDialog.Builder(activity).setTitle("操作日志").setItems(titles, new DialogInterface.OnClickListener() { @Override public void onClick(DialogInterface dialog, int which) { showDetail(activity, sp, which); } }).setNegativeButton("关闭", null).show(); }
private static void showDetail(final Activity activity, final SharedPreferences sp, int index) { final String title = sp.getString("title_" + index, "操作日志"); final String body = sp.getString("body_" + index, "暂无结果"); final TextView text = new TextView(activity); text.setText(body); text.setTextSize(14f); text.setTextIsSelectable(true); int pad = dp(activity, 14); text.setPadding(pad, dp(activity, 10), pad, dp(activity, 16)); final ScrollView scroll = new ScrollView(activity); scroll.setFillViewport(true); scroll.addView(text); final SeekBar seek = new SeekBar(activity); seek.setMax(1000); seek.setProgress(0); LinearLayout root = new LinearLayout(activity); root.setOrientation(LinearLayout.VERTICAL); root.addView(scroll); root.addView(seek); final boolean[] dragging = new boolean[] { false }; seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() { @Override public void onProgressChanged(SeekBar bar, int progress, boolean fromUser) { if (!fromUser) return; int range = Math.max(0, text.getHeight() - scroll.getHeight()); scroll.scrollTo(0, (int)(((long)range * progress) / 1000L)); } @Override public void onStartTrackingTouch(SeekBar bar) { dragging[0] = true; } @Override public void onStopTrackingTouch(SeekBar bar) { dragging[0] = false; } }); scroll.setOnScrollChangeListener(new View.OnScrollChangeListener() { @Override public void onScrollChange(View v, int sx, int sy, int oldx, int oldy) { if (dragging[0]) return; int range = Math.max(0, text.getHeight() - scroll.getHeight()); int progress = range <= 0 ? 0 : (int)(((long)sy * 1000L) / range); seek.setProgress(Math.max(0, Math.min(1000, progress))); } }); new AlertDialog.Builder(activity).setTitle(title).setView(root).setPositiveButton("复制", new DialogInterface.OnClickListener() { @Override public void onClick(DialogInterface dialog, int which) { Object service = activity.getSystemService(Context.CLIPBOARD_SERVICE); if (service instanceof ClipboardManager) ((ClipboardManager)service).setPrimaryClip(ClipData.newPlainText("操作日志", body)); } }).setNegativeButton("关闭", null).show(); }
private static int safeInt(String value) { try { return Integer.parseInt(value); } catch (Throwable ignored) { return 0; } }
private static String stamp(long now) { return new SimpleDateFormat("MM-dd HH:mm:ss", Locale.getDefault()).format(new Date(now)); }
private static String fullStamp(long now) { return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(new Date(now)); }
private static int dp(Context context, int value) { float d = context.getResources().getDisplayMetrics().density; return Math.max(1, (int)(value * d + 0.5f)); }
}
